[project]
name = "assignments"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "numba>=0.62.1",
    "numpy>=2.3.3",
    "pip>=25.2",
    "rocket-fft",
    "scipy>=1.16.1",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
